// <auto-generated />
using System;
using ASS_Bank_System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASS_Bank_System.Migrations
{
    [DbContext(typeof(AddDbContext))]
    partial class AddDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASS_Bank_System.Models.Account", b =>
                {
                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OpeningDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AccountNumber");

                    b.HasIndex("BranchCode");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountNumber = "A1001",
                            AccountType = "Savings",
                            BranchCode = "Z02",
                            CurrentBalance = 5000m,
                            OpeningDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("ASS_Bank_System.Models.Branch", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("Branchs");

                    b.HasData(
                        new
                        {
                            Code = "A01",
                            Address = "Cairo",
                            Name = "Main Branch",
                            PhoneNumber = "01242063325"
                        },
                        new
                        {
                            Code = "Z02",
                            Address = "Alex",
                            Name = "Z02 Branch",
                            PhoneNumber = "01023046981"
                        });
                });

            modelBuilder.Entity("ASS_Bank_System.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "Tanta",
                            CustomerType = "Individual",
                            DateOfBirth = new DateTime(2000, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mona@mail.com",
                            FullName = "Mona Mohamed",
                            NationalId = "12345678901234",
                            PhoneNumber = "01012345678"
                        });
                });

            modelBuilder.Entity("ASS_Bank_System.Models.CustomerAccount", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OwnershipStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OwnershipType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId", "AccountNumber");

                    b.HasIndex("AccountNumber");

                    b.ToTable("CustomerAccount");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            AccountNumber = "A1001",
                            AccountStatus = "Active",
                            OwnershipStartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            OwnershipType = "Primary"
                        });
                });

            modelBuilder.Entity("ASS_Bank_System.Models.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManagerId");

                    b.HasIndex("BranchCode")
                        .IsUnique();

                    b.ToTable("Managers");

                    b.HasData(
                        new
                        {
                            ManagerId = 1,
                            BranchCode = "A01",
                            Email = "Ahmed@mail.com",
                            FullName = "Ahmed",
                            HireDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "01242063325"
                        },
                        new
                        {
                            ManagerId = 2,
                            BranchCode = "Z02",
                            Email = "Mohamed@mail.com",
                            FullName = "Mohamed",
                            HireDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "01023046981"
                        });
                });

            modelBuilder.Entity("ASS_Bank_System.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionNumber"));

                    b.Property<string>("AccountNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransactionNumber");

                    b.HasIndex("AccountNum");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ASS_Bank_System.Models.Account", b =>
                {
                    b.HasOne("ASS_Bank_System.Models.Branch", "Branch")
                        .WithMany("Accounts")
                        .HasForeignKey("BranchCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("ASS_Bank_System.Models.CustomerAccount", b =>
                {
                    b.HasOne("ASS_Bank_System.Models.Account", "Account")
                        .WithMany("CustomerAccounts")
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ASS_Bank_System.Models.Customer", "Customer")
                        .WithMany("CustomerAccounts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ASS_Bank_System.Models.Manager", b =>
                {
                    b.HasOne("ASS_Bank_System.Models.Branch", "Branch")
                        .WithOne("Manager")
                        .HasForeignKey("ASS_Bank_System.Models.Manager", "BranchCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("ASS_Bank_System.Models.Transaction", b =>
                {
                    b.HasOne("ASS_Bank_System.Models.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountNum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("ASS_Bank_System.Models.Account", b =>
                {
                    b.Navigation("CustomerAccounts");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("ASS_Bank_System.Models.Branch", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("Manager")
                        .IsRequired();
                });

            modelBuilder.Entity("ASS_Bank_System.Models.Customer", b =>
                {
                    b.Navigation("CustomerAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
